# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vms.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvms.proto\x12\x06glonax\"\x07\n\x05\x45mpty\"\xcc\x01\n\x06Motion\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.glonax.Motion.MotionType\x12)\n\x07\x63hanges\x18\x02 \x03(\x0b\x32\x18.glonax.Motion.ChangeSet\x1a,\n\tChangeSet\x12\x10\n\x08\x61\x63tuator\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x11\"@\n\nMotionType\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08STOP_ALL\x10\x01\x12\x0e\n\nRESUME_ALL\x10\x02\x12\n\n\x06\x43HANGE\x10\x03\"\xec\x01\n\x06Signal\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\r\x12\x10\n\x08\x66unction\x18\x02 \x01(\r\x12\x15\n\x0btemperature\x18\n \x01(\x02H\x00\x12\x0f\n\x05\x61ngle\x18\x0b \x01(\x02H\x00\x12\x0f\n\x05speed\x18\x0c \x01(\x02H\x00\x12\r\n\x03rpm\x18\r \x01(\x05H\x00\x12.\n\x0c\x61\x63\x63\x65leration\x18\x0e \x01(\x0b\x32\x16.glonax.Signal.vector3H\x00\x12\x11\n\x07percent\x18\x0f \x01(\x05H\x00\x1a*\n\x07vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x42\x08\n\x06metric2x\n\x11VehicleManagement\x12\x30\n\rMotionCommand\x12\x0e.glonax.Motion\x1a\r.glonax.Empty\"\x00\x12\x31\n\x0cListenSignal\x12\r.glonax.Empty\x1a\x0e.glonax.Signal\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=21
  _EMPTY._serialized_end=28
  _MOTION._serialized_start=31
  _MOTION._serialized_end=235
  _MOTION_CHANGESET._serialized_start=125
  _MOTION_CHANGESET._serialized_end=169
  _MOTION_MOTIONTYPE._serialized_start=171
  _MOTION_MOTIONTYPE._serialized_end=235
  _SIGNAL._serialized_start=238
  _SIGNAL._serialized_end=474
  _SIGNAL_VECTOR3._serialized_start=422
  _SIGNAL_VECTOR3._serialized_end=464
  _VEHICLEMANAGEMENT._serialized_start=476
  _VEHICLEMANAGEMENT._serialized_end=596
# @@protoc_insertion_point(module_scope)
